global DEBUGPLOTS

clear MakeDebugPlot

DEBUGPLOTS.EstimateInsulinSecretion = struct(...
    'Uen', 1 ...
);


DEBUGPLOTS.FitHepaticClearance = struct(...
    'ForwardSim', 1, ...
    'nLxL', 1, ...
    'EquationTerms', 1, ...
    'MLRTerms', 1, ...
    'InsulinTerms', 1 ... 
);