function plots = DebugPlots(newPlots)

persistent DEBUGPLOTS;

if exist("newPlots", "var")
    DEBUGPLOTS = newPlots;
    
elseif isempty(DEBUGPLOTS)    
    DEBUGPLOTS.EstimateInsulinSecretion = struct(...
        'Uen', 1, ...
        'CPep', 1 ...
        );
    
    DEBUGPLOTS.FitHepaticClearance = struct(...
        'GraphicalID', 1, ...
        'Convergence', 1 ...
        );
    
    DEBUGPLOTS.FindOptimalHepaticClearance = struct(...
        'ErrorSurface', 1 ...
        );
    
    DEBUGPLOTS.LoadData = struct(...
        'GlucoseInput', 1 ...
        );
    
    DEBUGPLOTS.AnalyseInsulinVariance = struct(...
        'Error', 1 ...
        );
    
    DEBUGPLOTS.SolveSystem = struct(...
        'Glucose', 1, ...
        'Insulin', 1 ...
        );
    
    DEBUGPLOTS.FIGURES = [];    
end

plots = DEBUGPLOTS;

end