function plots = DebugPlots(newPlots)

persistent DEBUGPLOTS;

if exist("newPlots", "var")
    DEBUGPLOTS = newPlots;
    
elseif isempty(DEBUGPLOTS)    
    DEBUGPLOTS.EstimateInsulinSecretion = struct(...
        'Uen', 0, ...
        'CPep', 0 ...
        );
    
    DEBUGPLOTS.FitHepaticClearance = struct(...
        'GraphicalID', 0, ...
        'ForwardSim', 0, ...
        'Convergence', 0 ...
        );
    
    DEBUGPLOTS.FindOptimalHepaticClearance = struct(...
        'ErrorSurface', 0 ...
        );
    
    DEBUGPLOTS.LoadData = struct(...
        'GlucoseInput', 0 ...
        );
    
    DEBUGPLOTS.AnalyseInsulinVariance = struct(...
        'Error', 0 ...
        );
    
    DEBUGPLOTS.SolveSystem = struct(...
        'Glucose', 0, ...
        'Insulin', 0 ...
        );
    
    DEBUGPLOTS.FIGURES = [];    
end

plots = DEBUGPLOTS;

end